### PR TITLE
sys/ps: Use correct define for TLSF information.

### PR DESCRIPTION
**Pull request by jcarrano**
### Contribution description

I'm fixing my own bugs here.

The macro MODULE_TLSF_MALLOC indicates if tlsf is being used as the system-wide allocator. MODULE_TLSF only incates if TLSF is present.

PS should check for MODULE_TLSF_MALLOC to decide if heap information should be displayed.

### Issues/PRs references

The error was introduced in PR #9006.

### CODE REVIEW

**Comment by cgundogan** [comment]
again travis with
```
sys/ps/ps.c:84: error (cppcheckError): Analysis failed. If the code is valid then please report this failure.
```

ignoring, because it's a false positive.
