### PR TITLE
cpu/esp32: fix esp_wifi compile error

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR fixes a compilation error with the `esp_wifi` module enabled that was introduced with PR #12947.

### Testing procedure

The compilation error occurs when the `esp_wifi` module is enabled. This means that a successful compilation of any application with the `esp_wifi` module enabled is sufficient as a test.
```
USEMODULE='esp_wifi' make BOARD=esp32-wroom-32 -C tests/shell
```
fails without the PR and succeeds with this PR.

### Issues/PRs references

Fixes compilation problem of PR #12947.

### CODE REVIEW

**Comment by gschorcht** [comment]
@benpicco Sorry, before providing PR #12947, I renamed `tx_buf` to `_tx_buf` to indicate that it is an internal variable. Unfortunately, I did this after my last tests and haven't changed all its occurrences. I changed the name back with this PR.

**Comment by benpicco** [comment]
I'm surprised Murdock didn't catch this.
Isn't there some compile-test for this module?

**Comment by gschorcht** [comment]
Thanks for testing and merging sooooo fast :smile: 

> We should introduce some automatic compile-tests to prevent this in the future.

Yes, of course. I will provide one.
