### PR TITLE
drivers/ethos: fix build without ethos_stdio

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

Building `ethos` standalone (without `ethos_stdio`) is broken:

```
/home/benpicco/dev/RIOT/drivers/ethos/ethos.c: In function '_fail_frame':
/home/benpicco/dev/RIOT/drivers/ethos/ethos.c:92:25: error: 'ethos_stdio_isrpipe' undeclared (first use in this function)
   92 |             tsrb_clear(&ethos_stdio_isrpipe.tsrb);
      |                         ^~~~~~~~~~~~~~~~~~~
/home/benpicco/dev/RIOT/drivers/ethos/ethos.c:92:25: note: each undeclared identifier is reported only once for each function it appears in
/home/benpicco/dev/RIOT/drivers/ethos/ethos.c:95:13: error: implicit declaration of function 'isrpipe_write_one' [-Werror=implicit-function-declaration]
   95 |             isrpipe_write_one(&ethos_stdio_isrpipe, ETHOS_FRAME_DELIMITER);
      |             ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

due to a missing `#ifdef MODULE_ETHOS_STDIO`.

This fixes that and adds a compile test for standalone ethos so CI can catch future bugs.

### Issues/PRs references

fixes bug introduced with #17265

### CODE REVIEW

File: tests/driver_ethos/Makefile [hunk 1]
```diff
@@ -0,0 +1,7 @@
+# the radio driver to test
```
Comment (chrysn) [inline tests/driver_ethos/Makefile:1]:
```suggestion
# the network driver to test
```

File: tests/driver_ethos/Makefile [hunk 2]
```diff
@@ -0,0 +1,7 @@
...
+USEMODULE = ethos
+
+CFLAGS += -DETHOS_UART=UART_DEV\(1\)
```
Comment (chrysn) [inline tests/driver_ethos/Makefile:4]:
```suggestion
# This test's purpose is to demonstrate the use of EthOS on a different serial,
# without running stdio over it; consequently, it can only be used on boards
# that actually have two UARTs.
CFLAGS += -DETHOS_UART=UART_DEV\(1\)
```

**Review by chrysn — COMMENTED** [review]
Thanks, good catch and sorry for letting that slip by the review in the first place.

Trying this out on my microbit-v2 (obviously, in hindsight) failed for lack of a UART_DEV(1). Got any idea how, in one or two lines, these could be caught in something more helpful than an assertion? (Putting myself in the shoes of someone who fixes something around here later: They might `make all flash term` there with their board at hand, and start of befuddled why this test doesn't even pass before their changes).

File: tests/driver_ethos/Makefile (hunk 2 above)
Comment (benpicco) [reply tests/driver_ethos/Makefile]: let's better set those defaults in `ethos_params.h` the way slipdev does it.

**Comment by fjmolinas** [comment]
All green here @chrysn!

File: drivers/include/ethos.h [hunk 3]
```diff
@@ -55,6 +55,17 @@ extern "C" {
 #define ETHOS_BAUDRATE STDIO_UART_BAUDRATE
 #endif
 /** @} */
+#else
+#ifndef ETHOS_UART
+#if IS_USED(MODULE_USBUS_CDC_ACM)
+#define ETHOS_UART     UART_DEV(0)
```
Comment (chrysn) [inline drivers/include/ethos.h:61]: If I were to pick I'd probably put an error "On USB, there is proper Ethernet, please use that (or explicitly configure your UART device)" in her, but this is probably the more professional default.

**Review by chrysn — APPROVED** [review]

File: drivers/include/ethos.h (hunk 3 above)
Comment (benpicco) [reply drivers/include/ethos.h:61]: In this case USB would be used to connect to a PC but ethos (via UART) would be used to connect to another board

Comment (chrysn) [reply drivers/include/ethos.h:61]: Ah, so UART_DEV(0) is the physical UART on that board. Makes more sense then, as the "preferred" UART is in that case the high-numbered (from USB) while the low-numbered is the "secondary" one that gets the Ethernet.
