### PR TITLE
pkg/ccn-lite: bump version to fix compile error

### LINKED ISSUE #8627: ccn-lite: does not build on Ubuntu 16.04 (LTS)
#### Description
CCNlite currently does not build on the most current LTS version of Ubuntu for `native`:

#### Steps to reproduce the issue
```sh
BOARD=native make -C examples/ccn-lite-relay
```

#### Expected results
CMake should finish and CCN-lite should proceed to be build.

#### Actual results
CMake fails with:

```
[…]
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.7 or higher is required.  You are running version 3.5.1
[…]
```

#### Versions
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
$ uname -a
Linux sarajevo 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### PR DESCRIPTION
**Pull request by smlng**
### Contribution description

this PR updates the CCN-lite version to fix a compile issue found when using GCC 7.x and debug output, see here:

```
/RIOT/examples/ccn-lite-relay/bin/pkg/native/ccn-lite/src/ccnl-fwd/src/ccnl-dispatch.c:94:36: error: format '%zd' expects argument of type 'signed size_t', but argument 5 has type 'int' [-Werror=format=]
             DEBUGMSG_CORE(WARNING, "?unknown packet format? ccnl_core_RX ifndx=%d, %d bytes starting with 0x%02x at offset %zd\n",
                                    ^
                      ifndx, datalen, *data, data - base);
                                             ~~~~~~~~

```

I made a PR on the upstream repo of CCN-lite which is already merged, hence this PR update the package version accordingly.

### Issues/PRs references

for GCC7 compatibility see #8265, fixes #8627

### CODE REVIEW

**Comment by cgundogan** [comment]
can you please adjust the ccn-lite version, again?

**Comment by smlng** [comment]
@cgundogan done

**Comment by kYc0o** [comment]
What's missing here? @cgundogan do you ACK?

**Comment by miri64** [comment]
This fixes #8627 for me, so ACK from my side.

**Comment by miri64** [comment]
Gnarf, should have triggered a rebuild, let's hope I did not break anything by merging this 1-line change ^^"

**Comment by smlng** [comment]
🤞
