### PR TITLE
tests: Add test for irq_disable() / irq_restore()

### PR DESCRIPTION
**Pull request by maribu**
### Contribution description

As the title suggests: Adds a stupidly simple test to check if `irq_disable()` and `irq_restore()` work as intended.

### Testing procedure

`BOARD=<SOME_BOARD> make -C tests/irq_disable_restore flash term`

### Issues/PRs references

Useful to test https://github.com/RIOT-OS/RIOT/pull/13999

### CODE REVIEW

**Comment by maribu** [comment]
Unless I overlooked something, we had no test direct coverage for those two functions before. (Still, chances are good that every second tests fails if `irq_disable()` and `irq_restore()` won't work. But having a stupidly simple test that directly checks those two functions might be useful.)

File: tests/irq_disable_restore/README.md [hunk 1]
```diff
@@ -0,0 +1,13 @@
+# Test for `irq_disable()` and `irq_restore()`
+
+This test checks if `irq_disable()` and `irq_restore()` work as intended. For
+that, the test uses two variables *a* and *b*, both initialized with 0. The main
+test will schedule a timer that expires in *T/2*. It will than set *a* to 1 and
```
Comment (fjmolinas) [inline tests/irq_disable_restore/README.md:5]:
```suggestion
test will schedule a timer that expires in *T/2*. It will then set *a* to 1 and
```

**Comment by fjmolinas** [comment]
Will test on a bunch of boards ASAP.

**Comment by fjmolinas** [comment]
I have an issue with `fputs` on native:

```

Help: Press s to start test, r to print it is ready
READY
s
START
main(): This is RIOT! (Version: 2020.07-devel-378-g90618-pr-14011)
Test for irq_disable() / irq_restore()
======================================

[SUCCESS]
[SUCCESS]
Timeout in expect script at "child.expect_exact("Verifying test works: [SUCCESS]")" (tests/irq_disable_restore/tests/01-run.py:14)

```

**Comment by fjmolinas** [comment]
I have a compilation error on `msp430` boards, I don't really understand it..

`BUILD_IN_DOCKER=1 BOARD=z1 make -C tests/irq_disable_restore/`

```
/data/riotbuild/riotbase/cpu/msp430_common/include/stdatomic.h:212:9: error: expected specifier-qualifier-list before ‘int_least8_t’
/data/riotbuild/riotbase/cpu/msp430_common/include/stdatomic.h:213:9: error: expected specifier-qualifier-list before ‘uint_least8_t’
/data/riotbuild/riotbase/cpu/msp430_common/include/stdatomic.h:214:9: error: expected specifier-qualifier-list before ‘int_least16_t’
/data/riotbuild/riotbase/cpu/msp430_common/include/stdatomic.h:215:9: error: expected specifier-qualifier-list before ‘uint_least16_t’
/data/riotbuild/riotbase/cpu/msp430_common/include/stdatomic.h:216:9: error: expected specifier-qualifier-list before ‘int_least32_t’
/data/riotbuild/riotbase/cpu/msp430_common/include/stdatomic.h:217:9: error: expected specifier-qualifier-list before ‘uint_least32_t’
/data/riotbuild/riotbase/cpu/msp430_common/include/stdatomic.h:218:9: error: expected specifier-qualifier-list before ‘int_least64_t’
/data/riotbuild/riotbase/cpu/msp430_common/include/stdatomic.h:219:9: error: expected specifier-qualifier-list before ‘uint_least64_t’
...
```

**Comment by maribu** [comment]
> I have an issue with `fputs` on native:

I worked around this by using `fmt` for output. Using full blown `printf()` would increase ROM size quite a bit, so `fmt` seems to be the best option.

**Comment by fjmolinas** [comment]
Tested on these boards, only `z1` failed, will be fixed with #14012.

`nrf52840-mdk nrf52840dk slstk3402a nucleo-f091rc hifive1b remote-revb b-l072z-lrwan1 z1 nucleo-l152re nucleo-l433rc ek-lm4f120xl nucleo-f103rb i-nucleo-lrwan1 arduino-uno nucleo-f410rb arduino-zero frdm-k64f nucleo-f303re b-l475e-iot01a openmote-b stm32l476g-disco iotlab-m3 pba-d-01-kw2x nucleo-f207zg nrf52dk arduino-mega2560 nucleo-l073rz nucleo-f767zi`

**Comment by fjmolinas** [comment]
@maribu once #14012 is in please rebase and squash (and trigger murdock)!

**Comment by fjmolinas** [comment]
@maribu please rebase!

**Comment by maribu** [comment]
Looks like with llvm somehow `stdint.h` is not included implicitly with `stdatomic.h`. I'd say that newlib's `stdatomic.h` missing an `#include <stdint.h>` - but that would have to be fixed upstream. I work around this by just adding the include in `main.c`. I'll squash right away.

**Comment by maribu** [comment]
OK, in the log of test application that could be compiled a hint is given:

> tests/libc_newlib: blacklist esp32 boards temporarily
>
> ESP32 boards must be blacklisted for `tests/libc_newlib` to avoid CI compilation errors until the toolchain is updated on all nodes.

So I guess a toolchain update is still pending on

>-- running on worker breeze thread 11, build number 283085.

**Comment by fjmolinas** [comment]
> So I guess a toolchain update is still pending on
> 
> >-- running on worker breeze thread 11, build number 283085.
> 

@kaspar030 @cgundogan @aabadie @riot-ci  can you take a look?

**Comment by fjmolinas** [comment]
@maribu if its only one worker we could just re-schedule and hope for the best :D

**Comment by maribu** [comment]
The [single failed test](https://ci.riot-os.org/RIOT-OS/RIOT/14011/51c19d5b6b619af02ffde6f972a951de40e2db35/output/run_test/tests/pkg_littlefs2/esp32-wroom-32:gnu.txt) looks serious, but completely unrelated.

**Comment by fjmolinas** [comment]
> The single failed test looks serious, but completely unrelated.

FYI @gschorcht

**Comment by fjmolinas** [comment]
Ajj we got the faulty worker again.

**Comment by maribu** [comment]
> Ajj we got the faulty worker again.

Let's roll the dice again :-D

**Comment by maribu** [comment]
Thanks for the review :-)
