### PR TITLE
cpu/esp8266: removes netstats in esp wifi netdev driver

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR fixes the compilation error if `esp_wifi` module is enabled. With PR #9793, layer 2 netstats were moved from `netdev` drivers to `gnrc_netif`. This had also to be done for `esp_wifi`.

### Testing procedure

Since this PR fixes only a compilation problem, the compilation of `examples/gnrc_examples` should be enough as test, for example:
```
USEMODULE=esp_wifi make BOARD=esp8266-esp-12x -C examples/gnrc_networking 
```

### Issues/PRs references

Problem occurred with PR #9793.

### CODE REVIEW

File: cpu/esp8266/esp-wifi/esp_wifi_netdev.c [hunk 1]
```diff
@@ -455,18 +451,11 @@ static int IRAM _send(netdev_t *netdev, const iolist_t *iolist)
 
     if (res == ERR_OK) {
         /* There was no ieee80211_output_pbuf error and no send timeout. */
-#ifdef MODULE_NETSTATS_L2
-        netdev->stats.tx_bytes += iol_len;
-        netdev->event_callback(netdev, NETDEV_EVENT_TX_COMPLETE);
```
Comment (smlng) [inline cpu/esp8266/esp-wifi/esp_wifi_netdev.c]: this should stay in somehow, see other netdev implementations, e.g. also esp32 esp_wifi

Comment (gschorcht) [reply cpu/esp8266/esp-wifi/esp_wifi_netdev.c]: Yes, of course you are right, thanks.

**Comment by smlng** [comment]
please squash

**Comment by aabadie** [comment]
Sorry, I missed this PR. Since it's marked as a bug and is fixing a build failure, maybe a backport to 2019.01-branch is needed. What do you think ?

**Comment by gschorcht** [comment]
@aabadie Since it wasn't a bug in `esp_wifi` but a compilation problem introduced caused by PR #9793, there is no need to backport as long as PR #9793 is not backported.

**Comment by aabadie** [comment]
You are right @gschorcht, thanks for clarifying!
