### PR TITLE
cpu/native: fix build with afl-gcc 11.2

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

Building `fuzzing/gcoap` with afl-gcc 11.2 gives

```
/home/benpicco/dev/RIOT/cpu/native/native_cpu.c: In function ‘thread_stack_init’:
/home/benpicco/dev/RIOT/cpu/native/native_cpu.c:120:11: error: variable ‘stk’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
  120 |     char *stk = NULL;
      |           ^~~
/home/benpicco/dev/RIOT/cpu/native/native_cpu.c:118:72: error: argument ‘stack_start’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
  118 | char *thread_stack_init(thread_task_func_t task_func, void *arg, void *stack_start, int stacksize)
      |
```

We can re-write the function to not use this temporary variable and the error goes away.

### Testing procedure

Any `native` application should still run.
You can also build the fuzzing examples on a recent distribution again.

### CODE REVIEW

**Review by maribu — APPROVED** [review]
ACK. I see nothing in the diff that will change generated binaries, and if this is preferred by afl-gcc, than let's make afl-gcc happy :)
