### PR TITLE
core/kernel_defines: drop CONST definition

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

This is not used anywhere in RIOT, but causes conflicts with external library code.

So let's just get rid of this.

### Testing procedure

Green CI

### Issues/PRs references

Was introduced by #689

### CODE REVIEW

**Review by maribu — APPROVED** [review]
ACK. The use of `__attribute__((const))` on functions is also not supported by clang, still clang defines `__GNUC__` (which I personally find a bit upsetting...). So the implementation is also certainly broken.

The AVR libc is the only user of this I am aware of. It is useful for the compiler without LTO to know when an external function cannot access memory, e.g. the compiler can assume that global variables still have the same value after the function call and doesn't need to reload it from memory back into the register that was holding the value anyway.

But I really hope that we just enable LTO as default eventually. Then no functions will be external and the compiler can just check when it has to reload values and when not, without burdening the programmer of declaring access patterns.

**Review by kaspar030 — APPROVED** [review]
ACK.

Removing macros is always nice, especially if they're unused.

**Comment by aabadie** [comment]
According to Murdock, it seems that this macro is required for C++ applications.

**Comment by aabadie** [comment]
> it seems that this macro is required for C++ applications.

or maybe more:
```
In file included from tm.c:24:
../include/tm.h: In function 'tm_is_leap_year':
../include/tm.h:68:36: error: expected declaration specifiers before 'CONST'
   68 | int tm_is_leap_year(unsigned year) CONST;
```

**Comment by maribu** [comment]
It is used in `sys/include/tm.h`. Dropping it could lead to an increase in `.text` without LTO in some cases. But making LTO the default is on the roadmap anyway, so let's get the code simpler by just dropping it :)

**Comment by benpicco** [comment]
Ah I missed that one. Let’s rather rename it to `CONSTEXPR` since I think this was the intention here

**Comment by kaspar030** [comment]
I think constexpr is a relsted but different thing?
