### PR TITLE
Revert "sys/pm_layered: pm_(un)block add attribute optimize(3)"

### PR DESCRIPTION
**Pull request by Teufelchen1**
Revert "sys/pm_layered: pm_(un)block add attribute optimize(3) -shortens hotpath"

This reverts commit 5447203921ab39962d7d378a631a6bc048e7f30b.

### Contribution description

Compiling `examples/gnrc_networking_mac` using `TOOLCHAIN=llvm` yields the following error:
```
RIOT/sys/pm_layered/pm.c:77:16: error: unknown attribute 'optimize' ignored [-Werror,-Wunknown-attributes]
__attribute__((optimize(3)))
```
As indicated, this is because the attribute `optimize` is GCC only and not present in LLVM.
Compare the manpages of [GCC](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html) and [LLVM](https://clang.llvm.org/docs/AttributeReference.html).

### Testing procedure

Since this should only affect performance and not behavior, no special testing is needed. I am not aware of any tests in RIOT which could verify that assumption.

### Issues/PRs references

Introduced in #18846

There is another instance of this attribute being used in[ shell_lock.c](https://github.com/RIOT-OS/RIOT/blob/6fb340d654ac8da07759cb9199c6aaa478589aa7/sys/shell_lock/shell_lock.c#L80). Since the usage is security related, I omit it from this PR.

### CODE REVIEW

**Review by benpicco — APPROVED** [review]
@kfessel what difference doesn `-O3` even make here?
I can't think of that many different ways to optimize this.

I would assume most optimizations came from the proper alignment?

**Comment by benpicco** [comment]
> There is another instance of this attribute being used in `shell_lock.c`. Since the usage is security related, I omit it from this PR.

`shell_lock` is more of a tamper protection than real security. There is a [wanrning](https://doc.riot-os.org/group__sys__shell__lock.html) about this in the doc.

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Comment by maribu** [comment]
bors cancel
bors merge

(This should allow another PR to hop onto the merge train :steam_locomotive: :train: :train: :train:)

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors merge

**Comment by kfessel** [comment]
> @kfessel what difference doesn `-O3` even make here? I can't think of that many different ways to optimize this.
> 
> I would assume most optimizations came from the proper alignment?

the attribute shortens the hotpath by reordering instructions preferring the common case of not failing the assertion -> less jumps -> less loss of pipeline

**Comment by benpicco** [comment]
Uh sounds like we need 

```C
#define likely(x)       __builtin_expect((x),1)
#define unlikely(x)     __builtin_expect((x),0)
```

like Linux, then `assert()` would be 

```
#define assert(cond) (likely(cond) ? (void)0 : _assert_panic())
```

**Comment by kfessel** [comment]
we could use `#pragma GCC optimize(3)` (not per function but for the whole file) to achieve the same optimization without clang complaining

**Comment by kfessel** [comment]
another fix would be not to warn for unknown attributes in clang

**Comment by maribu** [comment]
Maybe we should just add `-Wno-error=unknown-attributes` when compiling with LLVM?

Otherwise this likely will be a whack-a-mole game, as we only compile-test with GCC.
