### ISSUE TITLE
assert: c99 static_assert macro doesn't function for multiple static_asserts in the same scope

### ISSUE THREAD

**Issue by pwillem** [RIOT-OS/RIOT#9371]
#### Description

c99 static assert introduced in 2bd1d7f045 doesn't allow multiple static_asserts in the same scope. GCC throws `/RIOT/core/include/assert.h:122:8: error: redeclaration of enumerator ‘static_assert_failed_on_div_by_0’`

#### Steps to reproduce the issue

1. add to examples/hello-world/main.c
``` C
 #include <stdio.h>
+#include <assert.h>

 int main(void)
 {
+    static_assert(sizeof(int) == sizeof(unsigned int), "int vs unsigned int");
+    static_assert(sizeof(int) != sizeof(long long int), "int vs long long int");
+
     puts("Hello World!");

     printf("You are running RIOT on a(n) %s board.\n", RIOT_BOARD);

```
2. make -C examples/hello-world
#### Expected results

example/hello-world should compile

#### Actual results

redeclaration error during compilation:
``` C
~/src/RIOT/examples/hello-world/main.c: In function ‘main’:
~/RIOT/core/include/assert.h:122:12: error: redeclaration of enumerator ‘static_assert_failed_on_div_by_0’
     enum { static_assert_failed_on_div_by_0 = 1 / (!!(cond)) }
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~/RIOT/examples/hello-world/main.c:28:5: note: in expansion of macro ‘static_assert’
     static_assert(sizeof(int) != sizeof(long long int), "int vs long long int");
     ^~~~~~~~~~~~~
~/RIOT/core/include/assert.h:122:12: note: previous definition of ‘static_assert_failed_on_div_by_0’ was here
     enum { static_assert_failed_on_div_by_0 = 1 / (!!(cond)) }
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~/RIOT/examples/hello-world/main.c:27:5: note: in expansion of macro ‘static_assert’
     static_assert(sizeof(int) == sizeof(unsigned int), "int vs unsigned int");
     ^~~~~~~~~~~~~
```
#### Versions

```
Installed compiler toolchains
-----------------------------
             native gcc: gcc (GCC) 8.1.1 20180531
      arm-none-eabi-gcc: arm-none-eabi-gcc (Arch Repository) 8.1.0
                avr-gcc: avr-gcc (GCC) 8.1.0
       mips-mti-elf-gcc: missing
             msp430-gcc: missing
   riscv-none-embed-gcc: missing
                  clang: clang version 6.0.0 (tags/RELEASE_600/final)

Installed compiler libs
-----------------------
   arm-none-eabi-newlib: "3.0.0"
    mips-mti-elf-newlib: missing
riscv-none-embed-newlib: missing
               avr-libc: cc1: fatal error: avr/version.h: No such file or directory
compilation terminated. (cc1: fatal error: avr/version.h: No such file or directory
compilation terminated.)

Installed development tools
---------------------------
                  cmake: cmake version 3.11.3
               cppcheck: Cppcheck 1.83
                doxygen: 1.8.14
                 flake8: missing
                    git: git version 2.17.1
             coccinelle: missing
```

**Comment by maribu** [comment]
I recall that I hit the same issue. But since we have now moved to `-std=c11`, we no longer have the fallback `static_assert()` macro in use. Instead, the C11 `_Static_assert()` is used as implementation, which works just fine with multiple instances in the same scope.
