### PR TITLE
cpu/arm7, arch/cortexm: Remove -fno-builtin flag

### PR DESCRIPTION
**Pull request by keith-packard**
### Contribution description

Re-enable compiler builtins for arm processors by removing the -fno-builtin flag from the arm7_common and cortexm makefile fragments.

The -fno-builtin flag disables all builtin functions provided by the compiler as well as disabling all optimizations and error checking related to standard C library functions. If you're using a C library which conforms to the ANSI C standard, you want to leave these compiler features enabled.

### Testing procedure

Pre-patch, note that printf calls are not optimized to puts calls (yeah, not a terribly helpful optimization, but it's how I discovered the issue):
```
$ sed -i '1a \
FEATURES_OPTIONAL += picolibc\
' examples/hello-world/Makefile
$ make -C examples/hello-world BOARD=microbit
$ nm -u examples/hello-world/bin/microbit/core_lib/init.o 
         U auto_init
         U cpu_switch_context_exit
         U main
         U printf
         U thread_create
```

Now apply the patch and check again:

```
$ make -C examples/hello-world BOARD=microbit
$ nm -u examples/hello-world/bin/microbit/core_lib/init.o 
         U auto_init
         U cpu_switch_context_exit
         U main
         U puts
         U thread_create
```

With the compiler able to use its knowledge about standard C library functions, it can convert the printf call in init.c which passes a constant string into a call to puts.

### Issues/PRs references

This PR references no outstanding issues.

### CODE REVIEW

**Comment by maribu** [comment]
@kaspar030 Do you happen to recall why `-fno-builtin` was added in the first place? If have to guess, I'd say that the compiler back than didn't honor the `-Os` optimization goal and generated a bigger binary for a given set of applications.

It is however quite difficult for the compiler to do match the `-Os` optimization goal when choosing to use builtins or `printf` without actually knowing which `printf` implementation it will link against.

I'm very much in favor of enabling builtins. Note that with `memset()` and `memcpy()` there are builtins where the compiler can greatly improve ROM size, especially since normally the C programmer can rely on `memset()` becoming a no-op if e.g. all struct members are manually initialized add adding a `memset()` has not runtime cost, but future proofs the code for when additional struct members are added that would otherwise be uninitialized.

I personally have always assumed that `memset()` and `memcpy()` are builtins and dead writes are properly eliminated by the optimizer.

**Comment by maribu** [comment]
MIPS and AVR are the other two arches where `-fno-builtin` is used. IMO we should drop that for all arches. (I'm not saying that this PR has to do this, though. But I wouldn't mind if it would also tackle those.)

**Comment by kaspar030** [comment]
> @kaspar030 Do you happen to recall why `-fno-builtin` was added in the first place? If have to guess, I'd say that the compiler back than didn't honor the `-Os` optimization goal and generated a bigger binary for a given set of applications.

Yeah, I think there was a time where the compiler recognized a memset(0) or memcpy like code pattern and replaced it with a function call. I guess we'd need to take a close look at some of our compiles, like, the scheduler benchmarks, if this still matters.
I'm all for removing `-fno-builtins`!

**Comment by maribu** [comment]
That's cool! It enables a couple of compile time tests that do indicate bugs previously missed :)

**Comment by kaspar030** [comment]
(re-running CI with tests on hardware, to get benchmark numbers)

**Comment by keith-packard** [comment]
> It is however quite difficult for the compiler to do match the `-Os` optimization goal when choosing to use builtins or `printf` without actually knowing which `printf` implementation it will link against.

Yeah, GCC doesn't appear to modify it's approach to printf optimizations based on the -O value applied, e.g. assuming that puts is always better than printf. But, the key is that it doesn't matter which underlying libc implementation is used for these compiler operations to be valid, all that it assumes is that libc follows the C standard for library functions.

**Comment by keith-packard** [comment]
> MIPS and AVR are the other two arches where `-fno-builtin` is used. IMO we should drop that for all arches. (I'm not saying that this PR has to do this, though. But I wouldn't mind if it would also tackle those.)

I didn't have any way to validate either of those two architectures, which is why I didn't include them, of course. And using GCC builtin logic does depend on libc following the C language standards, so you probably need to be a bit cautious with AVR at least.

**Comment by kaspar030** [comment]
So, my gcc 11.2.0 turns the data relocation and bss zero loops of `reset_vector_default()` into something more verbose, leading to 40b increase in `text`. This is building `tests/bench_sched_nop` for samr21-xpro.

I guess that's acceptable, and if we'd care enough, we could probably disable builtins just for that function. Not a blocker I guess.

**Comment by kaspar030** [comment]
I manually confirmed that the [test failure](https://ci.riot-os.org/RIOT-OS/RIOT/17898/b21e6242800fc6b5a78ee3226232ef8fdd95b03f/output/run_test/tests/thread_float/samr21-xpro:gnu.txt) is unrelated.

**Review by maribu — APPROVED** [review]
Let me throw in a second ACK.

**Comment by maribu** [comment]
@OlegHahm: Can we have this in for this release? Or should we wait till after hard feature freeze?

**Comment by kaspar030** [comment]
> @OlegHahm: Can we have this in for this release? Or should we wait till after hard feature freeze?

This does affect a lot, but it's a oneline change and we don't expect this to cause trouble. And if it does, it is easy to revert. IMO it can go in.

**Comment by maribu** [comment]
nobody complained, so go!

**Comment by fabian18** [comment]
I have just encountered the following error on `master`:
```
/home/fabian/forks/RIOT/drivers/periph_common/cpuid.c: In function 'cpuid_get':
/home/fabian/forks/RIOT/drivers/periph_common/cpuid.c:34:5: error: 'memcpy' offset [0, 11] is out of the bounds [0, 0] [-Werror=array-bounds]
   34 |     memcpy(id, (void *)CPUID_ADDR, CPUID_LEN);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
It can be reproduced with:
`rm -rf tests/periph_cpuid/bin/* && BOARD=nucleo-f767zi make -C tests/periph_cpuid/`

A `git bisect` led me here. Actually I can hardly imagine that this would have slipped through the CI. So it may also be my configuration. But can you confirm that, or does this not show up for you?

```
$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (Arch Repository) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by keith-packard** [comment]
> /home/fabian/forks/RIOT/drivers/periph_common/cpuid.c: In function 'cpuid_get':
> /home/fabian/forks/RIOT/drivers/periph_common/cpuid.c:34:5: error: 'memcpy' offset [0, 11] is out of the bounds [0, 0] [-Werror=array-bounds]
>    34 |     memcpy(id, (void *)CPUID_ADDR, CPUID_LEN);
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> cc1: all warnings being treated as errors

Now that builtins are enabled, the compiler is using its knowledge of memcpy to warn that this use isn't known to be in-bounds. So it's not surprising that removing -fno-builtin causes this message. What is a bit surprising is that this code triggers bounds detection concerns. Fix it could involve silencing the warning in this file (with a #pragma), or inserting casts to the operation.
