### ISSUE TITLE
ccn-lite: does not build on Ubuntu 16.04 (LTS)

### ISSUE THREAD

**Issue by miri64** [RIOT-OS/RIOT#8627]
#### Description
CCNlite currently does not build on the most current LTS version of Ubuntu for `native`:

#### Steps to reproduce the issue
```sh
BOARD=native make -C examples/ccn-lite-relay
```

#### Expected results
CMake should finish and CCN-lite should proceed to be build.

#### Actual results
CMake fails with:

```
[…]
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.7 or higher is required.  You are running version 3.5.1
[…]
```

#### Versions
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
$ uname -a
Linux sarajevo 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by miri64** [comment]
There is a fix in the CCN-lite repo (https://github.com/cn-uofbasel/ccn-lite/commit/d2ea61ff450d0f3636aa29af3e448ef10ee95f9e) but updating it to that commit, doesn't build either:

```
examples/ccn-lite-relay/bin/pkg/native/ccn-lite/src/ccnl-core/test/ccnl_core_test_prefix_comp_exact_match.c:43:5: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
 int main(){
     ^
examples/ccn-lite-relay/bin/pkg/native/ccn-lite/src/ccnl-core/test/ccnl_core_test_prefix_comp_exact_match.c: In function ‘main’:
examples/ccn-lite-relay/bin/pkg/native/ccn-lite/src/ccnl-core/test/ccnl_core_test_prefix_comp_exact_match.c:43:5: error: old-style function definition [-Werror=old-style-definition]
examples/ccn-lite-relay/bin/pkg/native/ccn-lite/src/ccnl-core/test/ccnl_core_test_prefix_comp_exact_match.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-implicit-fallthrough’ [-Werror]
cc1: error: unrecognized command line option ‘-Wno-implicit-fallthrough’ [-Werror]
cc1: all warnings being treated as errors
ccnl-core/CMakeFiles/ccnl_core_test_prefix_comp_exact_match.dir/build.make:62: recipe for target 'ccnl-core/CMakeFiles/ccnl_core_test_prefix_comp_exact_match.dir/test/ccnl_core_test_prefix_comp_exact_match.c.o' failed
make[4]: *** [ccnl-core/CMakeFiles/ccnl_core_test_prefix_comp_exact_match.dir/test/ccnl_core_test_prefix_comp_exact_match.c.o] Error 1
```

**Comment by miri64** [comment]
> Setting ccn-lite's PKG_VERSION to cn-uofbasel/ccn-lite@d2ea61f specific fixes the issue.

Done that in #8628.

**Comment by miri64** [comment]
Fixed in https://github.com/RIOT-OS/RIOT/pull/8427
