### PR TITLE
Fix NDEBUG compilation problems

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR fixes compilation problems when `NDEBUG` is defined.

Commit https://github.com/RIOT-OS/RIOT/pull/14364/commits/deb2d466c40422a3942062aafa55cc03a2379f9d is only for defining `NDEBUG` for compilation. It must be dropped before merge.

### Testing procedure

Compilation in CI has to succeed.

### CODE REVIEW

**Comment by gschorcht** [comment]
@miri64 I'm fixing all the problems step by step, and I'll probably push more commits until Murdock is satisfied.

**Comment by miri64** [comment]
I see. Then just tell me when its done :-)

**Comment by gschorcht** [comment]
@miri64 Compilation with `NDEBUG` is now successful. May I drop commit https://github.com/RIOT-OS/RIOT/pull/14364/commits/deb2d466c40422a3942062aafa55cc03a2379f9d for merging.

**Comment by miri64** [comment]
Yes please :-)

**Comment by gschorcht** [comment]
It's ready for merging but requires an approve.

File: pkg/u8g2/Makefile.u8g2_csrc [hunk 1]
```diff
@@ -1,6 +1,7 @@
 MODULE = u8g2_csrc
 
 CFLAGS += -Wno-overlength-strings
+CFLAGS += -Wno-unused-variable
```
Comment (miri64) [inline pkg/u8g2/Makefile.u8g2_csrc:4]: Please add documentation on why this flag is added (I know the previous does not either, but let's not repeat mistakes ;-))

Comment (miri64) [reply pkg/u8g2/Makefile.u8g2_csrc:4]: Ping @gschorcht?

Comment (gschorcht) [reply pkg/u8g2/Makefile.u8g2_csrc:4]: Hm, not really clear what comment could say more than this option.

Comment (miri64) [reply pkg/u8g2/Makefile.u8g2_csrc:4]: Why it was added, what needs to happen to remove the flag, maybe mention `NDEBUG`. ;-)

Comment (aabadie) [reply pkg/u8g2/Makefile.u8g2_csrc:4]: I agree with @gschorcht, there's no real need for a comment here. And this Makefile is building code from an external package, so I wouldn't care that much that there's an unused variable.

@gschorcht, please rebase on top of latest master so all new CI checks are triggered.

**Comment by fjmolinas** [comment]
@gschorcht do you mind giving this a rebase?

**Comment by kaspar030** [comment]
postponed

**Review by benpicco — APPROVED** [review]
looks good to me

**Comment by gschorcht** [comment]
> looks good to me

Thanks for approving but after rebasing and compiling with `NDEBUG` defined, a lot of new compilation errors pop up. I will go through and try to fix them first.

**Comment by gschorcht** [comment]
@benpicco Finally, I fixed the remaining issues in the commits provided today. Furthermore, I provided some small fixups. If you still give an ACK, I would squash them. After a further success of compilation in Mudock, I would remove commit 99c7941ff093cb3fa9b1d64f00d55cef8ae45585.

File: pkg/qr-code-generator/Makefile [hunk 2]
```diff
@@ -7,5 +7,10 @@ include $(RIOTBASE)/pkg/pkg.mk
 
 CFLAGS += -Wno-type-limits
 
+ifneq (,$(findstring NDEBUG,$(CFLAGS)))
+  # avoid compilation errors when NDEBUG is defined
+  CFLAGS += -Wno-unused-parameter
+endif
```
Comment (maribu) [inline pkg/qr-code-generator/Makefile:13]: IMO for packages we can just unconditionally disable warnings. We usually don't maintain the package code anyway, so we do not really profit from reading the warnings. Hence, there is IMO no reason to enable as many warnings as possible.

File: pkg/u8g2/Makefile.u8g2_csrc [hunk 3]
```diff
@@ -2,6 +2,11 @@ MODULE = u8g2_csrc
 
 CFLAGS += -Wno-overlength-strings
 
+ifneq (,$(findstring NDEBUG,$(CFLAGS)))
+  # avoid compilation errors when NDEBUG is defined
+  CFLAGS += -Wno-unused-variable
+endif
+
```
Comment (maribu) [inline pkg/u8g2/Makefile.u8g2_csrc:9]: same

File: pkg/wakaama/contrib/lwm2m_client.c [hunk 4]
```diff
@@ -171,6 +171,9 @@ static void *_lwm2m_client_run(void *arg)
         sock_udp_ep_t local;
         int res = sock_udp_get_local(&_client_data->sock, &local);
         assert(res >= 0);
+#if IS_ACTIVE(NDEBUG)
+        (void)res;
+#endif
```
Comment (maribu) [inline pkg/wakaama/contrib/lwm2m_client.c:176]: No need for preprocessor conditionals here, casting to `void` has no disadvantage for the case with assertions enabled, so it can just always be done.

**Review by maribu — COMMENTED** [review]
lgtm, comments are optional. Squash directly. I'll ACK once the testing commit is dropped.

File: pkg/qr-code-generator/Makefile (hunk 2 above)
Comment (gschorcht) [reply pkg/qr-code-generator/Makefile]: > lgtm, comments are optional. Squash directly. I'll ACK once the testing commit is dropped.

Rebase and testing commit removed.

**Review by maribu — APPROVED** [review]

**Comment by gschorcht** [comment]
Thanks for reviewing and merging.

**Comment by kaspar030** [comment]
Nice one, thanks a lot!
