### PR TITLE
FIB: Reduce scope of global vars to the scope of a fib_table

### PR DESCRIPTION
**Pull request by cgundogan**
This PR reduces the scope of `mtx_access`, `notify_rp_pos`, `notify_rp` and `prefix_rp`to that of a `fib_table_t`.
My intention was to make the mutex accessible through the table, so that other modules (in my case RPL) could iterate over the fib entries. While doing so for the mutex, I figured it would also make sense to reduce the scope of the other globals, so that there is no commonality between different fib tables.

### CODE REVIEW

**Comment by BytesGalore** [comment]
I'm not really convinced to let everyone directly iterate and access the FIB table entries (I have to think more about it)
Else I like the idea to group the global entries to table specific ones :)

**Comment by cgundogan** [comment]
I thought about adjusting the `fib_get_destination_set` function, because I don't have this prefix restriction anymore. So what I actually want is to include all fib entries in the DAO, but check for the RPL flag introduced in #4107 in order to set the `external` flag or not. Copying all entries like it's done in `fib_get_destination` is IMO a little bit of an over-kill. Just imagine several modules would need to lookup the fib entries .. this would result in several big buffers that must be supplied to the fib implementation for the memcpy :/

**Comment by BytesGalore** [comment]
> this would result in several big buffers that must be supplied to the fib implementation for the memcpy :/

true

**Comment by cgundogan** [comment]
>true

is this an ACK? (:

**Comment by BytesGalore** [comment]
not yet:
```
RIOT/tests/unittests/tests-fib/tests-fib.c:24:1: error: missing initializer for field ‘mtx_access’ of ‘fib_table_t’ [-Werror=missing-field-initializers]
 static fib_table_t test_fib_table = { _entries, TEST_FIB_TABLE_SIZE };
 ^

```

**Comment by BytesGalore** [comment]
regarding DAOs and the `fib_get_destination_set` out-buffer, 
reading between the lines you want to manually search and copy the matching addresses that are flagged?
I don't really see how this changes the out-buffer size situation else than that the non-flagged entries are skipped, which would be what I think usually only a single entry.

**Comment by cgundogan** [comment]
Not exactly. I want to copy all entries from the fib to the DAO but mark
those entries that weren't found via RPL with the `external` flag in the
transit option within the DAO
Am 19.10.2015 07:20 schrieb "BytesGalore" <notifications@github.com>:

**Comment by BytesGalore** [comment]
I think now I see the problem. The required information is obviously not passed by `fib_get destination_set()` since it only provides (copies) the raw address data of all matching entries.

Still I'm not happy that you have to get the entries manually.
The FIB has a flawed function here to receive the right entries, which would be completely obsolete if you have to copy the entries manually.

sorry for all this OT.

When the unittests pass, lets see what the CI bunch says and then ACK when they ACK :)

**Comment by cgundogan** [comment]
fixed and amended the unit test error

**Comment by BytesGalore** [comment]
Do we need to wait for the decision of strider? (Is strider armed and relevant for merges?)

**Comment by gebart** [comment]
Only Travis is required right now, as far as I know.

**Comment by BytesGalore** [comment]
@gebart thx for the info -> Go

**Comment by BytesGalore** [comment]
sorry wrong button
