### ISSUE TITLE
sys: tracker for ps.c printf mess

### ISSUE THREAD

**Issue by N8Fear** [RIOT-OS/RIOT#1907]
On cppcheck 1.67 I get:

```
sys/ps/ps.c:76: warning (invalidPrintfArgType_sint): %i in format string (no. 3) requires 'int' but the argument type is 'const char *'.
sys/ps/ps.c:76: warning (invalidPrintfArgType_sint): %i in format string (no. 4) requires 'int' but the argument type is 'const char *'.
sys/ps/ps.c:76: warning (wrongPrintfScanfArgNum): printf format string requires 7 parameters but 8 are given.
sys/ps/ps.c:76: warning (invalidPrintfArgType_p): %p in format string (no. 5) requires an address but the argument type is 'double'.
sys/ps/ps.c:76: warning (invalidPrintfArgType_float): %f in format string (no. 6) requires 'double' but the argument type is 'int'.
sys/ps/ps.c:76: error (wrongPrintfScanfArgNum): printf format string requires 7 parameters but only 6 are given.
```

Seems to be caused by #1815
