### PR TITLE
cpu/esp32: fix compilation errors in esp_eth

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR fixes one problem of CI compilation.

With [PR #227](https://github.com/RIOT-OS/riotdocker/pull/227) `riotdocker` was updated to GCC 12.2 . Obviously, following parts were not covered by compilation test before:

- [ ] `esp_eth`

### CODE REVIEW

**Comment by gschorcht** [comment]
bors try

**Comment by gschorcht** [comment]
bors try

**Comment by gschorcht** [comment]
bors try

**Review by maribu — APPROVED** [review]

**Comment by maribu** [comment]
bors cancel
bors merge

**Comment by maribu** [comment]
bors cancel
bors merge

(No other PR has been merged since the try, so no need to another full CI loop.)

**Comment by gschorcht** [comment]
Thanks, CI should now work with GCC 12.2 for ESP32x.
