### PR TITLE
pkg/relic: disable newline-eof compile error

### PR DESCRIPTION
**Pull request by smlng**
### Contribution description

Intermediate fix (package should be update anyways) for following error:

```
[ 64%] Building C object src/CMakeFiles/relic_s.dir/cp/relic_cp_ecdsa.c.obj
[ 65%] Building C object src/CMakeFiles/relic_s.dir/cp/relic_cp_ecss.c.obj
[ 66%] Building C object src/CMakeFiles/relic_s.dir/cp/relic_cp_vbnn_ibs.c.obj
/root/RIOT/tests/unittests/bin/pkg/native/relic/src/cp/relic_cp_vbnn_ibs.c:328:2: error: no newline at end of file [-Werror,-Wnewline-eof]
}
 ^
1 error generated.
src/CMakeFiles/relic_s.dir/build.make:1502: recipe for target 'src/CMakeFiles/relic_s.dir/cp/relic_cp_vbnn_ibs.c.obj' failed
```

### Issues/PRs references

package update in #6965

### CODE REVIEW

**Comment by smlng** [comment]
reported by `clang` on Ubuntu 16.04
```
cd tests/unittests
TOOLCHAIN=clang BOARDS=native make tests-relic
```

**Comment by miri64** [comment]
Does this require a backport?

**Comment by smlng** [comment]
```
root@808fb508ff3c:~/RIOT/tests/unittests# clang --version
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by miri64** [comment]
(if not remove flag, please)

**Comment by smlng** [comment]
> Does this require a backport?

Though we do not have `clang` as mandatory, I'm working on fixing clang and gcc 7.2 for this release. So yes, will do.
