### PR TITLE
Fix PSA Crypto Bugs

### PR DESCRIPTION
**Pull request by Einhornhool**
### Contribution description
This fixes several problems:

#### 1. Empty union in cipher context when `MODULE_PSA_CIPHER` is not selected.
PSA operations are now separated into modules. Functions and contexts are only built when the corresponding module is selected. This way there won't be problems with missing or unitialized structures in unused modules anymore.

#### 2. Empty array when using secure elements and `PSA_MAX_KEY_DATA_SIZE == 0`
I added a condition to the `psa_key_slot_t` structure in `psa_key_slot_management.h`.
Also the existence of key slot management functions and key slot structures now depends on the number of allocated key slots instead of selected modules.
This way key structures will not exist unless they are used.

#### 3. EdDSA and ECDSA examples fail when using a secure element because of unsopported changes introduced by #19954
Updated `example/psa_crypto` to use only supported functions for secure elements.

#### 4. Wrong public key size when using secure elements, introduced by  #19954
Fixed conditions for key size macros in `crypto_values.h`.

#### Fixes 1 and 2
Add the following to `examples/hello_world/Makefile` and call make : 
```
USEMODULE += psa_crypto
USEMODULE += psa_hash
USEMODULE += psa_hash_sha_256
USEMODULE += psa_secure_element
```
Output on Master:
```
"make" -C /home/lena/work/RIOT/boards/common/init
"make" -C /home/lena/work/RIOT/boards/native
"make" -C /home/lena/work/RIOT/boards/native/drivers
"make" -C /home/lena/work/RIOT/core
"make" -C /home/lena/work/RIOT/core/lib
"make" -C /home/lena/work/RIOT/cpu/native
"make" -C /home/lena/work/RIOT/cpu/native/periph
"make" -C /home/lena/work/RIOT/cpu/native/stdio_native
"make" -C /home/lena/work/RIOT/drivers
"make" -C /home/lena/work/RIOT/drivers/periph_common
"make" -C /home/lena/work/RIOT/sys
"make" -C /home/lena/work/RIOT/sys/auto_init
"make" -C /home/lena/work/RIOT/sys/libc
"make" -C /home/lena/work/RIOT/sys/luid
"make" -C /home/lena/work/RIOT/sys/preprocessor
"make" -C /home/lena/work/RIOT/sys/psa_crypto
In file included from /home/lena/work/RIOT/sys/include/psa_crypto/psa/crypto.h:39,
                 from /home/lena/work/RIOT/sys/psa_crypto/psa_crypto_algorithm_dispatch.c:23:
/home/lena/work/RIOT/sys/include/psa_crypto/psa/crypto_struct.h:137:11: error: union has no members [-Werror=pedantic]
  137 |     union cipher_context {
      |           ^~~~~~~~~~~~~~
In file included from /home/lena/work/RIOT/sys/psa_crypto/include/psa_crypto_operation_encoder.h:32,
                 from /home/lena/work/RIOT/sys/psa_crypto/psa_crypto_algorithm_dispatch.c:28:
/home/lena/work/RIOT/sys/psa_crypto/include/psa_crypto_slot_management.h:82:17: error: ISO C forbids zero-size array ‘data’ [-Werror=pedantic]
   82 |         uint8_t data[PSA_MAX_KEY_DATA_SIZE];    /**< Key data buffer */
      |                 ^~~~
cc1: all warnings being treated as errors
make[3]: *** [/home/lena/work/RIOT/Makefile.base:146: /home/lena/work/RIOT/examples/hello-world/bin/native/psa_crypto/psa_crypto_algorithm_dispatch.o] Error 1
make[2]: *** [/home/lena/work/RIOT/Makefile.base:31: ALL--/home/lena/work/RIOT/sys/psa_crypto] Error 2
make[1]: *** [/home/lena/work/RIOT/Makefile.base:31: ALL--/home/lena/work/RIOT/sys] Error 2
make: *** [/home/lena/work/RIOT/examples/hello-world/../../Makefile.include:761: application_hello-world.module] Error 2
```
Output with fixes:
```
"make" -C /home/lena/work/RIOT/boards/common/init
"make" -C /home/lena/work/RIOT/boards/native
"make" -C /home/lena/work/RIOT/boards/native/drivers
"make" -C /home/lena/work/RIOT/core
"make" -C /home/lena/work/RIOT/core/lib
"make" -C /home/lena/work/RIOT/cpu/native
"make" -C /home/lena/work/RIOT/cpu/native/periph
"make" -C /home/lena/work/RIOT/cpu/native/stdio_native
"make" -C /home/lena/work/RIOT/drivers
"make" -C /home/lena/work/RIOT/drivers/periph_common
"make" -C /home/lena/work/RIOT/sys
"make" -C /home/lena/work/RIOT/sys/auto_init
"make" -C /home/lena/work/RIOT/sys/libc
"make" -C /home/lena/work/RIOT/sys/luid
"make" -C /home/lena/work/RIOT/sys/preprocessor
"make" -C /home/lena/work/RIOT/sys/psa_crypto
"make" -C /home/lena/work/RIOT/sys/psa_crypto/psa_key_slot_mgmt
"make" -C /home/lena/work/RIOT/sys/psa_crypto/psa_se_mgmt
"make" -C /home/lena/work/RIOT/sys/random
/usr/bin/ld: warning: /home/lena/work/RIOT/examples/hello-world/bin/native/hello-world.elf has a LOAD segment with RWX permissions
   text	   data	    bss	    dec	    hex	filename
  29764	    584	  47856	  78204	  1317c	/home/lena/work/RIOT/examples/hello-world/bin/native/hello-world.elf
```
#### Fixes 3 and 4
Build `example/psa_crypto` for secure elements and run application

Output on master:
```
2023-10-19 13:29:06,900 # main(): This is RIOT! (Version: 2019.07-devel-22378-gb6772)
2023-10-19 13:29:06,900 # HMAC SHA256 took 56393 us
2023-10-19 13:29:06,900 # Cipher AES 128 took 68826 us
2023-10-19 13:29:06,901 # ECDSA took 51450 us
2023-10-19 13:29:06,901 # ECDSA failed: PSA_ERROR_GENERIC_ERROR
2023-10-19 13:29:06,901 # EdDSA took 37 us
2023-10-19 13:29:06,901 # EdDSA failed: PSA_ERROR_NOT_SUPPORTED
2023-10-19 13:29:06,901 # All Done
```
Output with fixes:
```
2023-10-19 13:35:24,715 # main(): This is RIOT! (Version: 2019.07-devel-22384-g8ef66-dev/psa-crypto-fixes)
2023-10-19 13:35:24,715 # HMAC SHA256 took 56374 us
2023-10-19 13:35:24,715 # Cipher AES 128 took 68805 us
2023-10-19 13:35:24,715 # ECDSA took 281164 us
2023-10-19 13:35:24,715 # All Done
```

### CODE REVIEW

**Comment by Einhornhool** [comment]
I'm realized that I should split this into two PRs, sorry for the inconvenience

File: sys/include/psa_crypto/psa/crypto_struct.h [hunk 1]
```diff
@@ -28,34 +28,7 @@ extern "C" {
...
- *
- * @return  struct psa_hash_operation_s
- */
-static inline struct psa_hash_operation_s psa_hash_operation_init(void)
-{
-    const struct psa_hash_operation_s v = PSA_HASH_OPERATION_INIT;
-
-    return v;
-}
-
```
Comment (MrKevinWeiss) [inline sys/include/psa_crypto/psa/crypto_struct.h:58]: Did you need to move this chunk below? Less changes that better (at least from the review perspective).

**Review by MrKevinWeiss — COMMENTED** [review]
Though I am not really in the PSA field I think it looks OK, and this does fix known issues.  only nitpick comments there...  Maybe it would be good to post the configurations that were tested.  If anyone else wants to go more in-depth that would be appreciated but it would be nice to get this backported for the release.  ping @Teufelchen1 maybe?

**Comment by mguetschow** [comment]
I get a lot of compile errors with the following configuration (copied from the initial post without the secure element):

```makefile
USEMODULE += psa_crypto
USEMODULE += psa_hash
USEMODULE += psa_hash_sha_256
```

**Review by mguetschow — CHANGES_REQUESTED** [review]
Here a somewhat more in-depth review. As discussed (off-thread) before, I am in favor of the suggested changes which compile more code only on-demand, hidden behind a small set of `PSA_<FEATURE>` module flags, which are quite easy to reason about.

The example of the failed compilation above is just another pointer to the fact that we definitely need some sort of configuration tests in a future PR.

File: sys/include/psa_crypto/psa/crypto_struct.h (hunk 1 above)
Comment (Einhornhool) [reply sys/include/psa_crypto/psa/crypto_struct.h:58]: I wanted to sort them by alphabet, but of course I can change this back

File: sys/psa_crypto/Makefile.dep [hunk 2]
```diff
@@ -256,7 +265,7 @@ endif
 # Secure Elements
 ifneq (,$(filter psa_secure_element,$(USEMODULE)))
   USEMODULE += psa_se_mgmt
-  USEMODULE += psa_key_slot_mgmt
+  USEMODULE += psa_key_management
```
[the remark this answers is not in the document]
Comment (Einhornhool) [reply sys/psa_crypto/Makefile.dep:268]: It's not really the same. I separate between the PSA key management functions which are described by the specification and are exposed to the user in `psa_crypto.c` and `psa/crypto.h` vs. the key *slot* management module, which contains the whole key slot logic and is its own backend module.

File: sys/psa_crypto/doc.txt [hunk 3]
```diff
@@ -438,10 +439,10 @@
  * In RIOT, module names are generated from path names, so if you create a directory for
  * your sourcefiles, the module name will be the same as the directory name. It is possible
  * to change that by declaring a new module name in the Makefile by adding the line
- * your_module_name`.
+ * `MODULE := your_module_name`.
```
[the remark this answers is not in the document]
Comment (Einhornhool) [reply sys/psa_crypto/doc.txt:442]: It is indirectly mentioned [here](https://github.com/RIOT-OS/RIOT/wiki/The-Make-Build-System), but I haven't found a more detailed explanation, yet. I kind of figured this out on my own by using modules and submodules.

File: sys/include/psa_crypto/psa/crypto_struct.h (hunk 1 above)
Comment (mguetschow) [reply sys/include/psa_crypto/psa/crypto_struct.h:58]: I think it makes sense to maintain the new order to only have one continuous block of hash-related things to be guarded by the if-directive.

File: sys/psa_crypto/psa_crypto.c [hunk 4]
```diff
@@ -1996,3 +2020,4 @@ psa_status_t psa_verify_message(psa_key_id_t key,
     unlock_status = psa_unlock_key_slot(slot);
     return ((status == PSA_SUCCESS) ? unlock_status : status);
 }
+#endif /* MODULE_PSA_ASYMMETRIC */
```
[the remark this answers is not in the document]
Comment (Einhornhool) [reply sys/psa_crypto/psa_crypto.c:2023]: I have thought about it at one point and I am totally not opposed to it. But you're right, it's a thing for the future.

File: sys/psa_crypto/doc.txt [hunk 5]
```diff
@@ -994,9 +998,11 @@
...
  * ifneq (,$(filter psa_secure_element_superse_ecc_p256, $(USEMODULE)))
- *   USEMODULE += psa_secure_element_asymmetric
+ *   USEMODULE += psa_asymmetric
  * endif
- *
- * Now the secure element should be available for use with PSA Crypto.
  * @endcode
+ * This needs to be done for all other supported operations (e.g. ATECCX08 operations in
+ * `pkg/cryptoauthlib/Makefile.include`, `pkg/cryptoauthlib/Makefile.dep` and
+ * `sys/psa_crypto/psa_se_mgmt/Kconfig` Now the secure element should be available for use
```
[the remark this answers is not in the document]
Comment (Einhornhool) [reply sys/psa_crypto/doc.txt]: Fixed

File: sys/psa_crypto/Kconfig.keys [hunk 6]
```diff
@@ -44,12 +49,11 @@ config PSA_PROTECTED_KEY_COUNT
 
 config PSA_ASYMMETRIC_KEYPAIR_COUNT
     int "Specifies number of allocated key pair slots"
-    default 5 if MODULE_PSA_ASYMMETRIC
     default 0
 
 config PSA_SINGLE_KEY_COUNT
     int "Specifies number of allocated single key slots"
-    default 5 if PSA_MAX_KEY_SIZE != 0
+    default 5 if MODULE_PSA_KEY_SLOT_MGMT
```
[the remark this answers is not in the document]
Comment (Einhornhool) [reply sys/psa_crypto/Kconfig.keys]: Fixed

File: sys/psa_crypto/psa_key_slot_mgmt/Kconfig [hunk 7]
```diff
@@ -7,4 +7,5 @@
 
 config MODULE_PSA_KEY_SLOT_MGMT
     bool
+    default y if MODULE_PSA_KEY_MANAGEMENT
```
[the remark this answers is not in the document]
Comment (Einhornhool) [reply sys/psa_crypto/psa_key_slot_mgmt/Kconfig]: fixed

File: sys/psa_crypto/psa_key_slot_mgmt/Kconfig [hunk 8]
```diff
@@ -7,4 +7,5 @@
...
     default y if PACKAGE_PSA_ARCH_TESTS
```
[the remark this answers is not in the document]
Comment (Einhornhool) [reply sys/psa_crypto/psa_key_slot_mgmt/Kconfig]: fixed

File: sys/psa_crypto/psa_crypto.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (mguetschow) [reply sys/psa_crypto/psa_crypto.c:2023]: Tracked in #20014

**Comment by MrKevinWeiss** [comment]
uggg it seems like we have some merge conflicts... I don't want to overwrite your commits.  When you have time rebase, I think I would just or the `SECURE_ELEMENT` flag with `#if IS_USED(MODULE_PSA_ASYMMETRIC_ECC_ED25519)`...

**Comment by Einhornhool** [comment]
> uggg it seems like we have some merge conflicts... I don't want to overwrite your commits. When you have time rebase, I think I would just or the `SECURE_ELEMENT` flag with `#if IS_USED(MODULE_PSA_ASYMMETRIC_ECC_ED25519)`...

Do you mean we have merge conflicts with master? Because I could just pull.

**Comment by MrKevinWeiss** [comment]
Then I would have to rebase on your commits.

**Comment by MrKevinWeiss** [comment]
ahh see, now my commit numbers will be inflated...

**Comment by Einhornhool** [comment]
> ahh see, now my commit numbers will be inflated...

Oh no. I also just did a rebase. Did I break anything?

**Review by mguetschow — APPROVED** [review]
LGTM, thanks for adding the configuration tests!

**Comment by MrKevinWeiss** [comment]
Since I contributed it would be nice to have a quick review from some other maintainer... cough cough @Teufelchen1

File: sys/include/psa_crypto/psa/crypto.h [hunk 9]
```diff
@@ -2476,7 +2488,9 @@ psa_status_t psa_hash_update(psa_hash_operation_t *operation,
 psa_status_t psa_hash_verify(psa_hash_operation_t *operation,
                              const uint8_t *hash,
                              size_t hash_length);
+#endif /* IS_USED(MODULE_PSA_HASH) */
```
Comment (Teufelchen1) [inline sys/include/psa_crypto/psa/crypto.h:2491]: Keeps the style consistent
```suggestion
#endif /* MODULE_PSA_HASH */
```

File: sys/include/psa_crypto/psa/crypto.h [hunk 10]
```diff
@@ -2619,7 +2633,9 @@ psa_status_t psa_import_key(const psa_key_attributes_t *attributes,
                             const uint8_t *data,
                             size_t data_length,
                             psa_key_id_t *key);
+#endif /* IS_USED(MODULE_PSA_KEY_MANAGEMENT) */
```
Comment (Teufelchen1) [inline sys/include/psa_crypto/psa/crypto.h:2636]:
```suggestion
#endif /* MODULE_PSA_KEY_MANAGEMENT */
```

File: sys/include/psa_crypto/psa/crypto_struct.h [hunk 11]
```diff
@@ -97,7 +70,9 @@ static inline struct psa_key_attributes_s psa_key_attributes_init(void)
 
     return v;
 }
+#endif
```
Comment (Teufelchen1) [inline sys/include/psa_crypto/psa/crypto_struct.h:73]:
```suggestion
#endif /*(MODULE_PSA_KEY_MANAGEMENT */
```

File: sys/include/psa_crypto/psa/crypto_struct.h [hunk 12]
```diff
@@ -124,7 +99,9 @@ static inline struct psa_aead_operation_s psa_aead_operation_init(void)
...
```
Comment (Teufelchen1) [inline sys/include/psa_crypto/psa/crypto_struct.h:102]:
```suggestion
#endif /* MODULE_PSA_AEAD */
```

File: sys/include/psa_crypto/psa/crypto_struct.h [hunk 13]
```diff
@@ -188,7 +165,39 @@ static inline struct psa_key_derivation_operation_s psa_key_derivation_operation
...
```
Comment (Teufelchen1) [inline sys/include/psa_crypto/psa/crypto_struct.h:168]:
```suggestion
#endif /* MODULE_PSA_KEY_DERIVATION */
```

File: sys/include/psa_crypto/psa/crypto_struct.h [hunk 14]
```diff
@@ -215,6 +224,7 @@ static inline struct psa_mac_operation_s psa_mac_operation_init(void)
...
```
Comment (Teufelchen1) [inline sys/include/psa_crypto/psa/crypto_struct.h:227]:
```suggestion
#endif /* MODULE_PSA_MAC */
```

File: sys/psa_crypto/include/psa_crypto_algorithm_dispatch.h [hunk 15]
```diff
@@ -68,7 +72,9 @@ psa_status_t psa_algorithm_dispatch_hash_finish(psa_hash_operation_t *operation,
                                                 uint8_t *hash,
                                                 size_t hash_size,
                                                 size_t *hash_length);
+#endif
```
Comment (Teufelchen1) [inline sys/psa_crypto/include/psa_crypto_algorithm_dispatch.h:75]:
```suggestion
#endif /* MODULE_PSA_HASH */
```

File: sys/psa_crypto/include/psa_crypto_algorithm_dispatch.h [hunk 16]
```diff
@@ -156,7 +162,9 @@ psa_status_t psa_algorithm_dispatch_verify_message( const psa_key_attributes_t *
                                                     size_t input_length,
                                                     const uint8_t *signature,
                                                     size_t signature_length);
+#endif
```
Comment (Teufelchen1) [inline sys/psa_crypto/include/psa_crypto_algorithm_dispatch.h:165]:
```suggestion
#endif /* MODULE_PSA_ASYMMETRIC */
```

File: sys/psa_crypto/include/psa_crypto_algorithm_dispatch.h [hunk 17]
```diff
@@ -213,7 +223,9 @@ psa_status_t psa_algorithm_dispatch_cipher_decrypt( const psa_key_attributes_t *
                                                     uint8_t *output,
                                                     size_t output_size,
                                                     size_t *output_length);
+#endif
```
Comment (Teufelchen1) [inline sys/psa_crypto/include/psa_crypto_algorithm_dispatch.h:226]:
```suggestion
#endif /* MODULE_PSA_CIPHER */
```

File: sys/psa_crypto/include/psa_crypto_location_dispatch.h [hunk 18]
```diff
@@ -116,7 +117,9 @@ psa_status_t psa_location_dispatch_verify_message(const psa_key_attributes_t *at
                                                  size_t input_length,
                                                  const uint8_t *signature,
                                                  size_t signature_length);
+#endif
```
Comment (Teufelchen1) [inline sys/psa_crypto/include/psa_crypto_location_dispatch.h:120]:
```suggestion
#endif /* MODULE_PSA_ASYMMETRIC */
```

File: sys/psa_crypto/include/psa_crypto_location_dispatch.h [hunk 19]
```diff
@@ -165,7 +170,9 @@ psa_status_t psa_location_dispatch_generate_key(const psa_key_attributes_t *attr
 psa_status_t psa_location_dispatch_import_key( const psa_key_attributes_t *attributes,
                                                const uint8_t *data, size_t data_length,
                                                psa_key_slot_t *slot, size_t *bits);
+#endif
```
Comment (Teufelchen1) [inline sys/psa_crypto/include/psa_crypto_location_dispatch.h:173]:
```suggestion
#endif /* MODULE_PSA_KEY_MANAGEMENT */
```

File: sys/psa_crypto/include/psa_crypto_location_dispatch.h [hunk 20]
```diff
@@ -254,6 +261,7 @@ psa_status_t psa_location_dispatch_cipher_decrypt(  const psa_key_attributes_t *
                                                     uint8_t *output,
                                                     size_t output_size,
                                                     size_t *output_length);
+#endif
```
Comment (Teufelchen1) [inline sys/psa_crypto/include/psa_crypto_location_dispatch.h:264]:
```suggestion
#endif /* MODULE_PSA_CIPHER */
```

**Review by Teufelchen1 — CHANGES_REQUESTED** [review]
Looks good! Only minor style errors remain.

**Review by Teufelchen1 — APPROVED** [review]

**Comment by MrKevinWeiss** [comment]
bors merge

**Comment by MrKevinWeiss** [comment]
Seems like you need to do some insufficient memory lists for the examples...

**Comment by MrKevinWeiss** [comment]
Let's hope the list is complete...

**Comment by MrKevinWeiss** [comment]
Let's hope the list is complete...

**Comment by MrKevinWeiss** [comment]
bors merge

**Comment by MrKevinWeiss** [comment]
It needs a rebase to get merged... Ping @Einhornhool

**Comment by Einhornhool** [comment]
> It needs a rebase to get merged... Ping @Einhornhool

Done

**Comment by MrKevinWeiss** [comment]
> > It needs a rebase to get merged... Ping @Einhornhool
> 
> Done

But also you dropped my commit adding the `makefile.ci` that add the insufficient boards to the list...

If you cannot recover that then I will try to find it (though I deleted the branch I can scrape the reflog maybe).

**Comment by MrKevinWeiss** [comment]
1. I will also remove this from the release backport... I think too much has changed already (new boards that may not exist in the release getting added to the insufficient memory list).

**Comment by Einhornhool** [comment]
> > > It needs a rebase to get merged... Ping @Einhornhool
> > 
> > 
> > Done
> 
> But also you dropped my commit adding the `makefile.ci` that add the insufficient boards to the list...
> 
> If you cannot recover that then I will try to find it (though I deleted the branch I can scrape the reflog maybe).

Oh shit, I'm sorry. How did that happen?? I'll see if I can find it

**Comment by mguetschow** [comment]
> > > > It needs a rebase to get merged... Ping @Einhornhool
> > > 
> > > 
> > > Done
> > 
> > 
> > But also you dropped my commit adding the `makefile.ci` that add the insufficient boards to the list...
> > If you cannot recover that then I will try to find it (though I deleted the branch I can scrape the reflog maybe).
> 
> Oh shit, I'm sorry. How did that happen?? I'll see if I can find it

It's still here: https://github.com/RIOT-OS/RIOT/commit/41f10d4c3f20168782ee08787ae6f92cfd86851b

**Comment by Einhornhool** [comment]
Readded the files

**Comment by Einhornhool** [comment]
@MrKevinWeiss I don't really understand that error thrown by Murdock. Is this something I need to take care of?

**Comment by MrKevinWeiss** [comment]
It is a unrelated issue I think. Murdock has been acting strange.

**Comment by MrKevinWeiss** [comment]
Looks like you need to add new boards (at least the `stm32f030f4-demo` to the `psa_crypto_ecdasa` and probably all but hashes...  This moving target is really an issue.  Worst case just whitelist boards instead.

**Comment by benpicco** [comment]
You can also run 

    make generate-Makefile.ci

**Comment by MrKevinWeiss** [comment]
whyyyyyyy!

**Comment by MrKevinWeiss** [comment]
Finally! Well done @Einhornhool

**Comment by mguetschow** [comment]
> whyyyyyyy!

Sorry that was me and the SHA512 support I guess :P congrats everyone that we have it in now!
