### ISSUE TITLE
Use-after-free in ccnl-core

### ISSUE THREAD

**Issue by chrysn** [RIOT-OS/RIOT#18480]
#### Description

With GCC 12.1.0, examples/ccn-lite-relay fails to build in the 2022.07 branch:

```
/home/chrysn/git/RIOT/build/pkg/ccn-lite/src/ccnl-core/src/ccnl-relay.c: In function ‘ccnl_content_remove’:
/home/chrysn/git/RIOT/build/pkg/ccn-lite/src/ccnl-core/src/ccnl-relay.c:547:66: error: pointer ‘c’ used after ‘free’ [-Werror=use-after-free]
  547 |     evtimer_del((evtimer_t *)(&ccnl_evtimer), (evtimer_event_t *)&c->evtmsg_cstimeout);
      |                                                                  ^~~~~~~~~~~~~~~~~~~~
In file included from /home/chrysn/git/RIOT/build/pkg/ccn-lite/src/ccnl-core/src/ccnl-relay.c:33:
/home/chrysn/git/RIOT/build/pkg/ccn-lite/src/ccnl-core/../ccnl-riot/include/ccn-lite-riot.h:52:41: note: call to ‘free’ here
   52 | #define ccnl_free(p)                    free(p)
      |                                         ^~~~~~~
/home/chrysn/git/RIOT/build/pkg/ccn-lite/src/ccnl-core/src/ccnl-relay.c:543:5: note: in expansion of macro ‘ccnl_free’
  543 |     ccnl_free(c);
      |     ^~~~~~~~~
cc1: all warnings being treated as errors
make[4]: *** [ccnl-core/CMakeFiles/ccnl-core.dir/build.make:356: ccnl-core/CMakeFiles/ccnl-core.dir/src/ccnl-relay.c.obj] Error 1
make[3]: *** [CMakeFiles/Makefile2:179: ccnl-core/CMakeFiles/ccnl-core.dir/all] Error 2
make[2]: *** [Makefile:91: all] Error 2
make[1]: *** [Makefile:28: /home/chrysn/git/RIOT/examples/ccn-lite-relay/bin/native/pkg-build/ccn-lite/lib/libccnl-riot.a] Error 2
make: *** [/home/chrysn/git/RIOT/examples/ccn-lite-relay/../../Makefile.include:802: pkg-build] Error 2
```

This happens with my local compiler, but not with BUILD_IN_DOCKER.

Chances are there's a use after free around that the newer compiler detects.
