### PR TITLE
tests : Add new test periph_gpio_arduino to allow testing of arduino pin numbering

### PR DESCRIPTION
**Pull request by TomKeddie**
Verified on Arduino uno.

2017-07-20 06:04:30,644 - INFO # Arduino GPIO peripheral driver test
2017-07-20 06:04:30,706 - INFO # In this test, pins are specified by integer pin numbers.
2017-07-20 06:04:30,771 - INFO # It uses a single integer to indicate the arduino digital pin.
2017-07-20 06:04:30,837 - INFO # NOTE: make sure the values you use exist on your platform! The
2017-07-20 06:04:30,898 - INFO #       behaviour for not existing ports/pins is not defined!

### CODE REVIEW

**Comment by smlng** [comment]
just a quick note, this does not compile on macOS with AVR 6.3.x:

```
$ BOARD=arduino-uno make clean all
Warning: no PORT set!
There are unsatisfied feature requirements: cpp


EXPECT ERRORS!


Building application "tests_periph_gpio_arduino" for "arduino-uno" with MCU "atmega328p".

In file included from /RIOT/drivers/include/periph/uart.h:49:0,
                 from /RIOT/sys/arduino/include/serialport.hpp:24,
                 from /RIOT/sys/arduino/include/arduino.hpp:29,
                 from /RIOT/tests/periph_gpio_arduino/_sketches.cpp:1:
/usr/local/Cellar/avr-gcc/6.3.0/lib/gcc/avr/6.3.0/include/stdint.h:9:26: fatal error: stdint.h: No such file or directory
 # include_next <stdint.h>
                          ^
compilation terminated.
make[1]: *** [/RIOT/tests/periph_gpio_arduino/bin/arduino-uno/tests_periph_gpio_arduino/_sketches.o] Error 1
make: *** [all] Error 2
```

I did not further investigate this right away, but will try to have a look in the next few days.

**Comment by gebart** [comment]
That looks like a tool chain issue on your side. Can you compile other examples and tests for avr on your machine?

**Comment by smlng** [comment]
> looks like a tool chain issue on your side

yeah very likely - but as always, I didn't do _anything_ and it worked in the past to compile RIOT for Arduinos 😉

**Comment by TomKeddie** [comment]
Back from vacation here.  I build it with the arduino toolchain.

ie.

```
[tom@z400 periph_gpio_arduino]$ PATH=~/.arduino15/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin:$PATH PORT=/dev/ttyACM0 BOARD=arduino-uno make
There are unsatisfied feature requirements: cpp


EXPECT ERRORS!


Building application "tests_periph_gpio_arduino" for "arduino-uno" with MCU "atmega328p".

"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/boards/arduino-uno
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/boards/arduino-atmega-common
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/core
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/cpu/atmega328p
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/cpu/atmega_common
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/cpu/atmega_common/periph
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/drivers
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/drivers/periph_common
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/sys
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/sys/arduino
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/sys/auto_init
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/sys/div
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/sys/isrpipe
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/sys/shell
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/sys/tsrb
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/sys/uart_stdio
"make" -C /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/sys/xtimer
   text    data     bss     dec     hex filename
   8448     962     869   10279    2827 /home/tom/git/TomKeddie/RIOT.test.periph_gpio_arduino/tests/periph_gpio_arduino/bin/arduino-uno/tests_periph_gpio_arduino.elf
```

**Comment by smlng** [comment]
FYI: tested again with new compiler and system setup, works fine now!

**Comment by smlng** [comment]
@dnahm and @lebrush you did lots of Arduino stuff lately, what's you opinion on this one?

**Comment by TomKeddie** [comment]
I should add I wrote this to test the arduino pin mapping when adding arduino support for a new board in https://github.com/RIOT-OS/RIOT/pull/7261

File: tests/periph_gpio_arduino/main.sketch [hunk 1]
```diff
@@ -0,0 +1,195 @@
+/*
+ * Copyright (C) 2017 Tom Keddie
+ * Copyright (C) 2014 Freie Universität Berlin
```
Comment (lebrush) [inline tests/periph_gpio_arduino/main.sketch]: I guess this Copyright line should go away

File: tests/periph_gpio_arduino/main.sketch [hunk 2]
```diff
@@ -0,0 +1,195 @@
...
+ * Public License v2.1. See the file LICENSE in the top level directory for more
+ * details.
+ */
+
+/**
+ * @ingroup     tests
+ * @{
+ *
+ * @file
+ * @brief       Manual test application for GPIO peripheral drivers using Arduino pin numbering
```
Comment (lebrush) [inline tests/periph_gpio_arduino/main.sketch]: This line is really long, please trim to 80 characters

Comment (TomKeddie) [reply tests/periph_gpio_arduino/main.sketch]: Thanks for the review, the code is base on the other gpio test, I dropped the copyright as requested, it's not clear to me which path to take here so advice is appreciated.

**Comment by TomKeddie** [comment]
@dnahm thanks, I'm confused about the appropriate fix here.  It seems like every board that provides arduino also implicitly provides cpp so should I add cpp to the provides for all the boards providing arduino? or something in the common Makefiles to automate this?  @smlng can you advise perhaps?  Thanks.

**Comment by smlng** [comment]
well, with board `arduino-due` it works, but that's no surprise because it has an ARM CPU (i.e. sam3) which uses arm-embedded-gcc and that has c++ support. However, other arduino boards such `arduino-uno` or `-mega2560` have AVR CPUs and use avr-gcc which by default does not have c++ support, right now. The `arduino` feature in RIOT requires feature `cpp` hence the error. 

So far so normal, IMHO the test is good.

**Comment by gebart** [comment]
Isn't the entire Arduino standard library written in c++?
I mean the original one from arduino.cc, for the atmega Arduinos like the Arduino Uno, duemilanove, mega2560, etc

**Comment by smlng** [comment]
IIRC there is no `stdatomic.h` for AVR - at least not without self-compiling - which is required to compile RIOTs C++ stuff, or not?

**Comment by kYc0o** [comment]
The Arduino IDE supports C++ since the first version, for Arduino uno. However I don't know if there is a code transformation to C somewhere, though I doubt it strongly because lots of libraries are written in C++ (which work with all the Arduino families).

I think the problem is that c++ is not supported in RIOT for AVR cpu's due to other reasons. A tracker exists in #1323.

**Comment by smlng** [comment]
what ever the problem with c++ on atmega Arduinos is, its not going to be solved in this PR, but it also should not block it either, right? 

So my ACK holds, please squash. @lebrush do you approve?

**Comment by lebrush** [comment]
Code and conceptwise looks good. I can test it today evening. Please @TomKeddie squash

**Comment by TomKeddie** [comment]
Thanks to all for your help.

**Comment by lebrush** [comment]
@TomKeddie please squash so we can test and merge it

**Comment by TomKeddie** [comment]
@lebrush apologies, am new to git..  Is done, I think I got that right.

**Comment by lebrush** [comment]
thanks @TomKeddie, I'll test it this evening :-)

File: tests/periph_gpio_arduino/main.sketch [hunk 3]
```diff
@@ -0,0 +1,195 @@
...
+ * @}
+ */
+
+#include <stdio.h>
+#include <stdlib.h>
+
+#include "shell.h"
+#include "periph/gpio.h"
+
+static int get_digital_pin(const char* pinstring, int* pin)
```
Comment (lebrush) [inline tests/periph_gpio_arduino/main.sketch]: It's a good idea to check whether the given parameter makes sense. Currently everything is accepted. It would be niced if you test whether the pinstring is a numerical character (since A pins are anyway not accepted).

**Comment by smlng** [comment]
I guess your request is addressed, do you approve @lebrush?

File: boards/sparkfun-samd21-mini/Makefile [hunk 4]
```diff
@@ -0,0 +1,3 @@
+MODULE = board
```
Comment (kaspar030) [inline boards/sparkfun-samd21-mini/Makefile]: Is this a new board? In that case it should go into seperate PR?

Comment (TomKeddie) [reply boards/sparkfun-samd21-mini/Makefile]: I've crossed my branches unfortunately.  Was not supposed to be here apologies.

**Comment by tcschmidt** [comment]
@TomKeddie can you address the change requests to get this moved?

**Comment by TomKeddie** [comment]
@tcschmidt I'll try to sort out the mess I made with the squash. Thanks for the poke.

**Comment by tcschmidt** [comment]
@miri64 can you help @TomKeddie with his Git problems?

**Comment by TomKeddie** [comment]
Replaced by https://github.com/RIOT-OS/RIOT/pull/9707
