### PR TITLE
cpu/stm32_common: add DMA support for all stm32

### PR DESCRIPTION
**Pull request by vincent-d**
### Contribution description

This adds DMA support for all stm32.
STDIO UART works fine on nucleo-f091 and on b-l072z-lrwan1. But SPI doesn't work on b-l072z-lrwan1, not tested on nucleo-f091.
I'm not sure I'll have a lot of time to continue this soon.

### Issues/PRs references

Follow-up #7658

### CODE REVIEW

**Comment by aabadie** [comment]
> I'm not sure I'll have a lot of time to continue this soon.

@vincent-d, is it still the case ?

**Comment by vincent-d** [comment]
> @vincent-d, is it still the case ?

Unfortunately, yes. But if you wish, you can take this over. It should be close to work.

**Comment by aabadie** [comment]
This PR needs a rebase.

I can confirm that DMA is not working with SPI on b-l072z-lrwan1. I didn't try either the f091.
I briefly looked at the code but have no idea what's wrong. It will require more investigation.

Otherwise, while looking at the code (correct me if I'm wrong), I have the impression that once periph_dma is required, all UART and SPI devices have to provide a configuration for it.
Would it be more simple/flexible that to make use of DMA in the periph implementation (spi.c/uart.c) only if a define (UART_USE_DMA, SPI_USE_DMA) is set in the board peripheral configuration.
This way it will be possible to keep DMA for UART on b-l072z-lrwan1 but not for SPI (since it doesn't work).

What do you think ?

**Comment by vincent-d** [comment]
> Otherwise, while looking at the code (correct me if I'm wrong), I have the impression that once periph_dma is required, all UART and SPI devices have to provide a configuration for it.

I haven't re-checked it, but as far as I remember, it should be possible to disable dma per uart or spi, in that case, the dma field should be set to `DMA_STREAM_UNDEF`.

File: boards/b-l072z-lrwan1/Makefile.features [hunk 1]
```diff
@@ -1,4 +1,6 @@
 # Put defined MCU peripherals here (in alphabetical order)
+FEATURES_PROVIDED += periph_dma
+FEATURES_PROVIDED += periph_gpio periph_gpio_irq
```
Comment (aabadie) [inline boards/b-l072z-lrwan1/Makefile.features]: This line is not needed anymore (see #10637)

File: boards/nucleo-f091rc/Makefile.features [hunk 2]
```diff
@@ -1,5 +1,7 @@
 # Put defined MCU peripherals here (in alphabetical order)
 FEATURES_PROVIDED += periph_adc
+FEATURES_PROVIDED += periph_dma
+FEATURES_PROVIDED += periph_gpio periph_gpio_irq
```
Comment (aabadie) [inline boards/nucleo-f091rc/Makefile.features]: This line is not needed anymore (see #10637)

File: boards/b-l072z-lrwan1/Makefile.features (hunk 1 above)
Comment (vincent-d) [reply boards/b-l072z-lrwan1/Makefile.features]: fixed

File: boards/nucleo-f091rc/Makefile.features (hunk 2 above)
Comment (vincent-d) [reply boards/nucleo-f091rc/Makefile.features]: fixed

**Comment by vincent-d** [comment]
>  We should fix this driver (and maybe others?) before merging this PR.

I don't know why it has been implemented like that in the first place. I can provide a quick fix though.

**Comment by vincent-d** [comment]
A quick grep shows that `cc110x` and `sc127x` use `irq_disable/irq_restore` around spi transfers. So they should be fixed.

**Comment by vincent-d** [comment]
I finally found the remaining issue!

It was a stupid mistake with the channel selection when 2 streams were used at the same time.

It finally works with b-l072z-lrwan1!

I guess I should split the drivers (cc110x and sx127x) parts in one (or 2) PR?

**Comment by aabadie** [comment]
> I guess I should split the drivers (cc110x and sx127x) parts in one (or 2) PR?

One PR for each would be better. Great that you could fix all issues.

**Comment by vincent-d** [comment]
See #10669 and #10670

File: cpu/stm32_common/periph/dma.c [hunk 3]
```diff
@@ -24,14 +24,61 @@
 #include "periph_conf.h"
 #include "mutex.h"
 #include "assert.h"
+#include "pm_layered.h"
 
-#if !(defined(CPU_FAM_STM32F2) || defined(CPU_FAM_STM32F4) || defined(CPU_FAM_STM32F7))
+#if !(defined(CPU_FAM_STM32F2) || defined(CPU_FAM_STM32F4) || defined(CPU_FAM_STM32F7) \
```
Comment (aabadie) [inline cpu/stm32_common/periph/dma.c]:
```suggestion
#if CPU_FAM_STM32F3
#error "DMA is not supported on STM32F3 CPU"
#endif
```

**Comment by vincent-d** [comment]
Cherry-picked some commits from @aabadie and updated config for `b-l475-iot01a`, STDIO UART works fine, SPI and second UART are not tested.

**Comment by aabadie** [comment]
> I triggered Murdock to check if there are not any build issue but I think it will be fine.

So Murdock found a remaining issue with C++ and the UART configuration struct, the dma related attributes were not at the right place for b-l072z-lrwan1 and b-l475e-iot01a boards. I (force) pushed 
2d79213 to fix that.

Now everything is fine. You can squash at any time (be careful the branches have diverged).

**Comment by vincent-d** [comment]
Rebased and squashed

**Comment by aabadie** [comment]
CI is all green, let's go!

**Comment by vincent-d** [comment]
Thanks @aabadie !

**Comment by cladmi** [comment]
A git bisect pointed me to the commit https://github.com/RIOT-OS/RIOT/commit/0b6bccb5430ab888b7a4e76424be94c878b42673 as breaking the `thread` tests for `iotlab-m3`.

I used this test to find the commit:

    BOARD=iotlab-m3 make -C tests/thread_basic/ all flash test

Also these other ones are failing but did not bisect them.

```
- [tests/cond_order](tests/cond_order/test.failed)
- [tests/isr_yield_higher](tests/isr_yield_higher/test.failed)
- [tests/msg_try_receive](tests/msg_try_receive/test.failed)
- [tests/mutex_order](tests/mutex_order/test.failed)
- [tests/pipe](tests/pipe/test.failed)
- [tests/posix_semaphore](tests/posix_semaphore/test.failed)
- [tests/ps_schedstatistics](tests/ps_schedstatistics/test.failed)
- [tests/pthread_barrier](tests/pthread_barrier/test.failed)
- [tests/pthread_cooperation](tests/pthread_cooperation/test.failed)
- [tests/pthread_rwlock](tests/pthread_rwlock/test.failed)
- [tests/rmutex](tests/rmutex/test.failed)
- [tests/thread_basic](tests/thread_basic/test.failed)
- [tests/thread_exit](tests/thread_exit/test.failed)
- [tests/thread_flags](tests/thread_flags/test.failed)
- [tests/thread_msg](tests/thread_msg/test.failed)
- [tests/thread_msg_seq](tests/thread_msg_seq/test.failed)
```


It also showed me that the commit https://github.com/RIOT-OS/RIOT/commit/08a85fbfddb3d3e0ab787e46fa2b6a5a176639af cannot compile as I guess required changes are introduced later.

```
/home/harter/work/git/RIOT/cpu/stm32_common/periph/uart.c:207:35: error: 'USART_ISR_TXE' undeclared (first use in this function); did you mean 'USART_SR_TXE'?
     while (!(dev(uart)->ISR_REG & USART_ISR_TXE)) {}
                                   ^~~~~~~~~~~~~
                                   USART_SR_TXE
/home/harter/work/git/RIOT/cpu/stm32_common/periph/uart.c:207:35: note: each undeclared identifier is reported only once for each function it appears in
```
